allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  14b3e6ee-55d2-4f37-8501-f7dfe0ca11e3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bec6e3e1-64de-4ba9-9a24-8a6ff66efe2e # Items Limit
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f0029a7-1698-4ebe-a2ed-e34e7af6b4c3
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: afcfeefb-37c5-467b-acb1-5c19ae4588ca # Items Per Page
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d37947bf-4670-46bc-b365-549e545f6d93
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 028c68a9-8240-4b8c-94d5-bca16475d037 # Collection Order By
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9ceca01-544f-4dec-b503-7bc56399d2fa
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 02738ded-dcec-472d-97d9-d171c58653b1 # Events Scope
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e184832-6665-4561-bc7e-0fcd87d4b032
            userCondition: null
            warning: null
            width: 25
        name: Collection
        uid: b813d138-3133-48fc-bdaa-796c29a09c5d
        userCondition: null
    thumbFieldKey: null
handle: eventsCollection
hasTitleField: false
icon: calendar
name: 'Events Collection'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Events
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
