allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  03bba916-63c3-4d24-80df-9008a5545c0a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8cf92812-2463-4c11-a9fe-4fe3e5639938
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7de1aa36-fe1f-4d28-b98e-4d1e7123d0e9 # Rich Text
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49d8c8bf-f0c7-4a0f-9482-cded33017c9e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 067c30b9-53c6-468f-8437-bb5c2524f667
        userCondition: null
    thumbFieldKey: null
handle: faq
hasTitleField: true
icon: circle-question
name: FAQ
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
