allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  8bcc117e-5f1e-46ab-97a3-5c0ab6f1029b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 73da4001-cb9a-49b9-94a1-9b49ad937de6 # Tab Label
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 116c3071-f710-4906-8024-f16de623d85c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8f90746f-df77-4301-8220-07d63cdbdd52 # Form
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c79bebca-13a8-43e6-a495-afb285a36986
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7a852395-4f12-458d-9496-5ecde5ba37d1
        userCondition: null
    thumbFieldKey: null
handle: formItem
hasTitleField: false
icon: rectangle-list
name: 'Form Item'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{tabLabel}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{tabLabel}'
