allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  22aa8196-8b17-4b3b-9d7a-3a678f552bd0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-08-05T07:38:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8c06fd93-fb2c-4ce5-a452-3c69b9488d6a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T11:18:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7de1aa36-fe1f-4d28-b98e-4d1e7123d0e9 # Rich Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab84c812-c3d0-44a1-88f9-4423f188cc9f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T11:17:04+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ddaaf76d-17ae-425d-bed5-2d8c1c70cc52 # Legal Items
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16507aaf-2a16-42b7-b136-c9945c4e84ce
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 238f9db8-3d9f-440f-95f5-f9dbd6aa6bff
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-05T07:38:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f449dbcf-eb13-43c8-a358-c47c6c2bc803 # SEO Title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f807a56d-6008-44fc-b74b-76bdf2e0e604
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T07:38:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bbe63ff6-f6c8-4d3f-9f3f-73af141d9aaf # SEO Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98198094-aee1-4413-bbcf-d2cc659b91df
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T07:38:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 04a59516-2675-475c-a81f-2549be9366e5 # SEO Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 271f2f63-1e1a-4fc1-a76a-8444dbfba725
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T07:38:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c7050a81-352d-4f95-b1b2-c96b6137211b # Open Graph Title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d56aa79e-07a6-4ad6-a914-bf7ce3fc21f9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T07:38:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8108f4f8-30f0-478c-8560-657c3b5baaf5 # Open Graph Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ac251dd-6eac-4dee-9693-6f89cf68debe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T07:38:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2fbc1e92-b23b-43af-9e98-0cbc96b8d39f # Open Graph Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9db6a73b-7118-471f-a3b7-ffb075853091
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T07:38:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f471f094-85f5-49d8-ba7a-40f531353884 # No Index
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95091f38-7f6f-430d-8d1f-dc0b1c27e0b9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T07:38:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 181882b1-9cfc-4e14-abba-b02e469f7239 # No Follow
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7cd59890-29d0-4803-8d04-329de1fb5d5f
            userCondition: null
            warning: null
            width: 50
        name: SEO
        uid: 0c95aaaa-2d9f-47f9-a0b1-bf360b30323b
        userCondition: null
    thumbFieldKey: null
handle: legalPage
hasTitleField: true
icon: scale-balanced
name: 'Legal Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
