allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  acf88ccd-8e27-41a1-b52f-b7856c4b0713:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ba8ace72-8081-4bf7-aa0b-706e69fc77e0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9bc2bd8f-3ecd-4c26-963b-70ed9439ec20 # Description
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1517fe80-e1e9-4a37-af16-bec5986973c6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f1449682-bc74-46dc-96bd-10e7565a474f
        userCondition: null
    thumbFieldKey: null
handle: listItem
hasTitleField: true
icon: list
name: 'List Item'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
