allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  2e10d131-3bdc-432d-bf9d-638fa6617fbd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 51e14688-17a6-434d-8948-7c1e445cc80b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1c5ecf2b-b376-4c3e-9fe7-37f8763ae1f7 # About Variant
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6390679-8180-42e5-a7c8-29baf5475a79
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b2d1edb5-4b8c-42be-8296-841cab61ef56 # Caption
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42bd8733-4680-4b61-a6d1-48c163d95afb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7de1aa36-fe1f-4d28-b98e-4d1e7123d0e9 # Rich Text
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f9981f9-3953-4ce9-bf2d-54fadc822b90
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dc4d4eed-0559-4bec-8d42-7fdfb693f8d3 # Images
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed53a032-12b8-45a1-bc0d-ba5025819b65
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dc2bd2ac-7d35-4080-931a-5c637f1686d5
        userCondition: null
    thumbFieldKey: null
handle: sectionAbout
hasTitleField: true
icon: table-columns
name: 'Section About'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
