allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  ec17c2f4-33e2-4775-8596-314944848522:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f8385c6c-1917-4b0f-8ebc-b648d22fc70e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b2d1edb5-4b8c-42be-8296-841cab61ef56 # Caption
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3117f85d-3444-415f-b486-ce911e56502f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7de1aa36-fe1f-4d28-b98e-4d1e7123d0e9 # Rich Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 659030b6-5c95-4782-aadd-aaec1e4d19dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 10bbb803-4d23-4599-8785-f2e62a66ce00 # Selected Events
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca0448f3-145a-4bbf-abc3-98e2730793d5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3ddb6fa2-895e-4cb8-a071-da27e99b0b4a # Items Limit
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5cb72ce-f63b-4139-b90d-80ffd43b2f1a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 83e70c17-a574-4eb4-8f04-14f618cf155d # Order By
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8133f81-cc00-487a-89dd-77c343241a57
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 83e1f5e8-d1b5-4776-89f9-bdbb1e113638 # Section Variant
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 209906e5-5824-4319-8ee9-aee37e18c503
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6f4fd0ee-dca6-41bc-9a7d-a027e3e1077f # Links
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 505212f4-e9d6-4074-a200-114fe9ab64dd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a1a88c6a-72bb-4e08-98f4-9bc3167a031c
        userCondition: null
    thumbFieldKey: null
handle: sectionEvents
hasTitleField: true
icon: calendar-days
name: 'Section Events'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
