allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  9401bb1e-df9c-4ddd-98a6-9a9e21093f6a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 457d22ce-f616-4671-abc9-f432efc3a0ee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3af62cab-8b90-42ca-b80f-cd57a4fca5d5 # Subtitle
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 337686b4-c6b2-492a-bb61-7cc4ff4e3302
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9bc2bd8f-3ecd-4c26-963b-70ed9439ec20 # Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 654a6f7a-967e-4d54-92b1-7e8f2861fbc5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fe1e327f-f713-41a4-8ed3-eaac7c941b7b # Image
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27f99bf4-f467-4de1-a556-c44241ca10f7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6f4fd0ee-dca6-41bc-9a7d-a027e3e1077f # Links
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 854b1fe5-39bd-4eda-a697-fb630eec392c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 07d5f2ea-fbd3-42b3-bdfa-d74ef94bdf5e # Custom Spacing
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75a7d7ff-d47d-45c7-8fa9-b9ea80d6b49d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 63b4f0ed-ea91-4662-bd31-c4d993c26bfe # Space Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4badbea4-3219-41dd-8faf-5fc82c39328c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 80449db7-9d3f-481c-a438-64d7616f2102 # Space Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d58cd74-8086-43fd-9ca9-c258fd1fb241
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: cceb72f6-affd-4e2d-997e-bebbafbc32df
        userCondition: null
    thumbFieldKey: null
handle: sectionHero
hasTitleField: true
icon: image
name: 'Section Hero'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
