allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  d7c695a9-4209-432d-ab30-2734f20fe7d5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 422e867e-bcdd-4ece-aa1c-3207c8a8a0d5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f1720845-8ddc-4032-bddc-1cd1eb098b56 # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37d63488-3083-40c1-8b93-8794807411a2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6f4fd0ee-dca6-41bc-9a7d-a027e3e1077f # Links
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aef6932f-4466-4bef-af71-3e8e41dd108f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 07d5f2ea-fbd3-42b3-bdfa-d74ef94bdf5e # Custom Spacing
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b78b0979-6921-4934-9c22-1bfdd9a6f09f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 63b4f0ed-ea91-4662-bd31-c4d993c26bfe # Space Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13b72c1b-ce91-4775-92c2-d899a6b33ac6
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 80449db7-9d3f-481c-a438-64d7616f2102 # Space Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc3f9a60-752b-4fca-bdd1-63cd59ce45fc
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: a548a5a7-bb3a-4d33-bf11-398b113aa617
        userCondition: null
    thumbFieldKey: null
handle: sectionTextCta
hasTitleField: true
icon: text
name: 'Section CTA Text'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
