allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  fc702ca1-c1b3-4323-8b42-ad2a07e87527:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bec6e3e1-64de-4ba9-9a24-8a6ff66efe2e # Items Limit
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8706e5d-7247-40f7-9643-6d0187ba9ec3
            userCondition: null
            warning: null
            width: 33
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: afcfeefb-37c5-467b-acb1-5c19ae4588ca # Items Per Page
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68169879-cf1b-415b-9a3a-793f30a4abb8
            userCondition: null
            warning: null
            width: 33
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7e37d166-4cec-4c6a-9402-4f3289179816 # Team Order By
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7f84614-54dc-4c50-a466-c8fc398be699
            userCondition: null
            warning: null
            width: 33
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 59f60dec-b0e8-4f31-aeeb-04148da14744 # Team Categories
            handle: null
            instructions: 'Optionally restrict the collection to selected categories.'
            label: 'Filter by Team Categories'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4d3dc6a-a419-4117-9c3d-8ad5776cfc7f
            userCondition: null
            warning: null
            width: 100
        name: Collection
        uid: 92b2c76c-04fa-477d-8a07-c33f990fd57a
        userCondition: null
    thumbFieldKey: null
handle: teamCollection
hasTitleField: false
icon: users
name: 'Team Collection'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Team
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
