columnSuffix: null
handle: aboutVariant
instructions: null
name: 'About Variant'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - SingleImageSmall
        -
          - value
          - singleImageSmall
        -
          - default
          - true
    -
      __assoc__:
        -
          - label
          - SingleImageLarge
        -
          - value
          - singleImageLarge
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - DoubleImage
        -
          - value
          - doubleImage
        -
          - default
          - false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
