columnSuffix: null
handle: accordionItems
instructions: null
name: 'Accordion Items'
searchable: false
settings:
  createButtonLabel: 'Add an accordion item'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - b416651f-9b88-4297-a63a-05a10cd372b3 # Accordion Item
        -
          - group
          - Legal
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
