columnSuffix: null
handle: legalItems
instructions: null
name: 'Legal Items'
searchable: false
settings:
  createButtonLabel: 'Add a legal item'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 8d10d191-fcb4-4900-90cd-aabc3f02b2fe # Legal Item
        -
          - group
          - Legal
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
