columnSuffix: null
handle: sectionImageSliderItems
instructions: null
name: 'Section Image Slider Items'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 244019eb-73b0-4ea5-976f-2592c3f2a9a8 # Image Slide
        -
          - group
          - Items
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
