columnSuffix: null
handle: sections
instructions: null
name: Sections
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 9f753c5c-df7d-4198-8a6c-682d90b5207b # Section Hero
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - 8a95c56e-9efa-4c74-afa7-dc065b39c23a # Section About
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - 98055765-f8b4-4c53-8033-574ac496e7d5 # Section CTA Slider
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - d8e0e1ac-ccfa-47a0-8342-b29270a8307e # Section CTA Text
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - 4eb068df-aa04-4606-9686-5d3cbd0b22c6 # Section Contact
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - 597f5647-6a7f-43ea-ad1c-d9d5fcbd521e # Section News
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - 1846e99c-13ed-4174-9745-46d95e002e3c # Section Values
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - 2ef7a896-ac7b-40fc-b4d1-48eb76976258 # Section Expertise
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - e7610728-1427-49bb-a0eb-6d551bdae3ed # Section Services
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - 009ebc2b-18fe-4485-a27d-156d91a1d4ac # Section List
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - ba5af5e7-826d-4038-ada5-372bb4bb7b7b # Section Events
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - f5b15a0e-8bf3-45a4-ba38-2dfefd0b356f # Section News And Events
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - 6b058ab9-7af1-4f82-a103-4d806604cf63 # Section Team
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - e26f7668-a7f6-4f48-8919-177a5910c732 # Section Image Slider
        -
          - group
          - Sections
    -
      __assoc__:
        -
          - uid
          - 56d14e66-247f-45a4-9a20-0dd5eb33d4bc # Section Reference
        -
          - group
          - Sections
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
