defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d1203fd6-b650-4a1a-b0d7-c8531d4ddcde # FAQ
handle: helpCenter
maxAuthors: 1
name: 'Help Center'
propagationMethod: all
siteSettings:
  1f9dcaf3-3f9d-4e81-996d-7bb1aefe81c8: # Ubiq Next
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
