defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9f753c5c-df7d-4198-8a6c-682d90b5207b # Section Hero
  -
    uid: 8a95c56e-9efa-4c74-afa7-dc065b39c23a # Section About
  -
    uid: 98055765-f8b4-4c53-8033-574ac496e7d5 # Section CTA Slider
  -
    uid: d8e0e1ac-ccfa-47a0-8342-b29270a8307e # Section CTA Text
  -
    uid: 4eb068df-aa04-4606-9686-5d3cbd0b22c6 # Section Contact
  -
    uid: 597f5647-6a7f-43ea-ad1c-d9d5fcbd521e # Section News
  -
    uid: 1846e99c-13ed-4174-9745-46d95e002e3c # Section Values
  -
    uid: 2ef7a896-ac7b-40fc-b4d1-48eb76976258 # Section Expertise
  -
    uid: e7610728-1427-49bb-a0eb-6d551bdae3ed # Section Services
  -
    uid: 009ebc2b-18fe-4485-a27d-156d91a1d4ac # Section List
  -
    uid: ba5af5e7-826d-4038-ada5-372bb4bb7b7b # Section Events
  -
    uid: f5b15a0e-8bf3-45a4-ba38-2dfefd0b356f # Section News And Events
  -
    uid: 6b058ab9-7af1-4f82-a103-4d806604cf63 # Section Team
  -
    uid: e26f7668-a7f6-4f48-8919-177a5910c732 # Section Image Slider
handle: reusableSections
maxAuthors: 1
name: 'Reusable Sections'
propagationMethod: all
siteSettings:
  1f9dcaf3-3f9d-4e81-996d-7bb1aefe81c8: # Ubiq Next
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
