defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 54262b9c-4f17-4e76-a5f1-9e148931ba48 # Team Member
handle: teamMembers
maxAuthors: 1
name: 'Team Members'
propagationMethod: all
siteSettings:
  1f9dcaf3-3f9d-4e81-996d-7bb1aefe81c8: # Ubiq Next
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
