isPublic: false
name: NextJs
scope:
  - 'sites.1f9dcaf3-3f9d-4e81-996d-7bb1aefe81c8:read' # Ubiq Next
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.2ff02e44-9d61-41bd-bf2c-5d7434a838d2:read' # Navigations
  - 'sections.bbe74a36-5c8c-4b60-8191-579ce8df7265:read' # News
  - 'sections.60b20bac-64e8-4103-8fbb-afa9a4cfacf7:read' # Pages
  - 'sections.0e026e73-9c8a-42a9-8750-396dc0f8f17a:read' # Reusable Sections
  - 'nestedentryfields.7de1aa36-fe1f-4d28-b98e-4d1e7123d0e9:read' # Rich Text
  - 'nestedentryfields.6f4fd0ee-dca6-41bc-9a7d-a027e3e1077f:read' # Links
  - 'nestedentryfields.30d1b8b2-bc92-4f54-a3fe-b915f5a0ce9d:read' # Navigation Items
  - 'nestedentryfields.360652e6-00ff-4774-b5c7-d9ad1331e09b:read' # Sections
  - 'nestedentryfields.92bae2f9-15a0-4712-a3df-69a3d0357913:read' # Social Links
  - 'volumes.f9f4c0c9-6e35-42b7-91b6-232b6b0068a4:read' # Uploads
  - 'globalsets.691eebac-34af-4bd3-bbd9-eac59b884edb:read' # Footer
  - 'globalsets.0c783779-c106-449f-b292-e9dbd9f195e4:read' # Legal
  - 'globalsets.56cd8fce-1035-4c04-9a6b-05704a65ca51:read' # SEO
  - 'globalsets.6376b934-148c-462e-a7b6-d8d6877bacdc:read' # Error Page
  - 'freeformForms.all:read'
  - 'freeformForms.464b5690-3349-4956-a97c-f9d0ecc73d2e:read'
  - 'freeformSubmissions.all:create'
  - 'freeformSubmissions.464b5690-3349-4956-a97c-f9d0ecc73d2e:create'
  - 'directive:transform'
  - 'sections.77da1a78-3cb7-42b4-9cbe-ff150a889293:read' # Services
  - 'sections.f45fa3cb-26fb-400f-a1d9-c9c47f7504b0:read' # Team Members
  - 'sections.b47c14a1-1115-4cf7-8d10-0f81c1f34c52:read' # Events
  - 'sections.03f4831e-7eb9-43d9-afdd-7831d4a2c11b:read' # Expertise
  - 'nestedentryfields.27138272-d22e-47c6-87e0-48c80581d80f:read' # Related Links
  - 'nestedentryfields.ddaaf76d-17ae-425d-bed5-2d8c1c70cc52:read' # Legal Items
  - 'nestedentryfields.d53bb36f-6fa0-4a78-8059-02622005bcfd:read' # Accordion Items
  - 'nestedentryfields.abdba094-401c-4d18-a918-e8d2e40dbdc9:read' # Collection
  - 'categorygroups.507722fb-06cd-4f93-a2c5-f1e5a09221bb:read' # Team Categories
  - 'nestedentryfields.55e5181d-ba5a-4f10-a7bc-b8fd27e6f57d:read' # CTA Slides
  - 'nestedentryfields.319aaf82-22ec-4714-9b18-84501766a0ac:read'
